import { DiscEnum } from '../../models/discEnum';
import MostLeastQuestionsModel from '../../models/mostLeastQuestionsModel'

export const QuestionsList = [
    new MostLeastQuestionsModel(1,
    DiscEnum.S, DiscEnum.S, "Easy-going, Agreeable",
    DiscEnum.I, DiscEnum.I, "Trusting, Believing in others",
    DiscEnum.Star, DiscEnum.D, "Adventurous, Risk taker",
    DiscEnum.C, DiscEnum.C, "Tolerant, Respectful"),
    new MostLeastQuestionsModel(2,
    DiscEnum.D, DiscEnum.D, "Results are what matter",
    DiscEnum.C, DiscEnum.C, "Do it right, Accuracy counts",
    DiscEnum.Star, DiscEnum.I, "Make it enjoyable",
    DiscEnum.Star2, DiscEnum.S, "Let's do it together"),
    new MostLeastQuestionsModel(3,
    DiscEnum.Star, DiscEnum.C, "Education, Culture",
    DiscEnum.D, DiscEnum.D, "Achievements, Awards",
    DiscEnum.S, DiscEnum.S, "Safety, Security",
    DiscEnum.I, DiscEnum.Star, "Social, Group Gatherings"),

    new MostLeastQuestionsModel(4,
    DiscEnum.C, DiscEnum.Star, "Soft spoken, Reserved",
    DiscEnum.D, DiscEnum.D, "Optimistic, Visionary",
    DiscEnum.Star, DiscEnum.I, "Center of attention, Sociable",
    DiscEnum.S, DiscEnum.S, "Peacemaker, Bring harmony"),
    new MostLeastQuestionsModel(5,
    DiscEnum.Star, DiscEnum.C, "Will do without, Self-controlled",
    DiscEnum.D, DiscEnum.D, "Will buy on impulse",
    DiscEnum.S, DiscEnum.S, "Will wait, No pressure",
    DiscEnum.I, DiscEnum.Star, "Will spend on what I want"),
    new MostLeastQuestionsModel(6,
    DiscEnum.D, DiscEnum.D, "Take charge, Direct approach",
    DiscEnum.Star, DiscEnum.I, "Outgoing, Enthusiastic",
    DiscEnum.Star2, DiscEnum.D, "Predictable, Consistent",
    DiscEnum.C, DiscEnum.Star, "Cautious, Careful"),

    new MostLeastQuestionsModel(7,
    DiscEnum.S, DiscEnum.S, "Encourage other",
    DiscEnum.I, DiscEnum.I, "Strive for perfection",
    DiscEnum.Star, DiscEnum.D, "Be part of the team",
    DiscEnum.C, DiscEnum.D, "Want to establish goals"),
    new MostLeastQuestionsModel(8,
    DiscEnum.S, DiscEnum.S, "Friendly, Easy to be with",
    DiscEnum.I, DiscEnum.I, "Unique, Bored by routine",
    DiscEnum.Star, DiscEnum.D, "Actively change things",
    DiscEnum.C, DiscEnum.D, "Want things exact"),
    new MostLeastQuestionsModel(9,
    DiscEnum.S, DiscEnum.S, "Not easily defeated",
    DiscEnum.I, DiscEnum.I, "Will do as told, Follows leader",
    DiscEnum.Star, DiscEnum.D, "Excitable, Cheerful",
    DiscEnum.C, DiscEnum.D, "Want things orderly, Neat"),

    new MostLeastQuestionsModel(10,
    DiscEnum.S, DiscEnum.S, "Become frustrated",
    DiscEnum.I, DiscEnum.I, "Keep my feelings inside",
    DiscEnum.Star, DiscEnum.D, "Tell my side of the story",
    DiscEnum.C, DiscEnum.D, "Stand up to opposition"),
    new MostLeastQuestionsModel(11,
    DiscEnum.S, DiscEnum.S, "Non-confrontational, Giving in",
    DiscEnum.I, DiscEnum.I, "Overloaded wit details",
    DiscEnum.Star, DiscEnum.D, "Changes at the last minute",
    DiscEnum.C, DiscEnum.D, "Demanding, Abrupt"),
    new MostLeastQuestionsModel(12,
    DiscEnum.S, DiscEnum.S, "I will lead them",
    DiscEnum.I, DiscEnum.I, "I will follow through",
    DiscEnum.Star, DiscEnum.D, "I will persuade them",
    DiscEnum.C, DiscEnum.D, "I will get the facts"),

    new MostLeastQuestionsModel(13,
    DiscEnum.S, DiscEnum.S, "Lively, Talkative",
    DiscEnum.I, DiscEnum.I, "Fast paced, Determined",
    DiscEnum.Star, DiscEnum.D, "Try to maintain balance",
    DiscEnum.C, DiscEnum.D, "Try to follow the rules"),
    new MostLeastQuestionsModel(14,
    DiscEnum.S, DiscEnum.S, "Want advancement",
    DiscEnum.I, DiscEnum.I, "Satisfied with things, Content",
    DiscEnum.Star, DiscEnum.D, "Openly display feelings",
    DiscEnum.C, DiscEnum.D, "Humble, Modest"),
    new MostLeastQuestionsModel(15,
    DiscEnum.S, DiscEnum.S, "Thing of others first",
    DiscEnum.I, DiscEnum.I, "Competitive, Like a challenge",
    DiscEnum.Star, DiscEnum.D, "Optimistic, Positive",
    DiscEnum.C, DiscEnum.D, "Logical thinker, Systematic"),

    new MostLeastQuestionsModel(16,
    DiscEnum.S, DiscEnum.S, "Manage time efficiently",
    DiscEnum.I, DiscEnum.I, "Often rushed, Feel pressured",
    DiscEnum.Star, DiscEnum.D, "Social things are important",
    DiscEnum.C, DiscEnum.D, "Like to finish what I start"),
    new MostLeastQuestionsModel(17,
    DiscEnum.S, DiscEnum.S, "Cool, Reserved",
    DiscEnum.I, DiscEnum.I, "Happy, Carefree",
    DiscEnum.Star, DiscEnum.D, "Pleasing, Kind",
    DiscEnum.C, DiscEnum.D, "Bold, Daring"),
    new MostLeastQuestionsModel(18,
    DiscEnum.S, DiscEnum.S, "Please others, Agreeable",
    DiscEnum.I, DiscEnum.I, "Laugh out loud, Animated",
    DiscEnum.Star, DiscEnum.D, "Courageous, Bold",
    DiscEnum.C, DiscEnum.D, "Quiet, Reserved"),

    new MostLeastQuestionsModel(19,
    DiscEnum.S, DiscEnum.S, "Resist sudden change",
    DiscEnum.I, DiscEnum.I, "Tend to over promise",
    DiscEnum.Star, DiscEnum.D, "Withdraw under pressure",
    DiscEnum.C, DiscEnum.D, "Not afraid to fight"),
    new MostLeastQuestionsModel(20,
    DiscEnum.S, DiscEnum.S, "Spend quality time with others",
    DiscEnum.I, DiscEnum.I, "Plan for the future, Be prepared",
    DiscEnum.Star, DiscEnum.D, "Travel to new adventures",
    DiscEnum.C, DiscEnum.D, "Receive rewards for goals met"),
    new MostLeastQuestionsModel(21,
    DiscEnum.S, DiscEnum.S, "Want more authority",
    DiscEnum.I, DiscEnum.I, "Want new opportunities",
    DiscEnum.Star, DiscEnum.D, "Avoid any conflict",
    DiscEnum.C, DiscEnum.D, "Want clear directions"),

    new MostLeastQuestionsModel(22,
    DiscEnum.S, DiscEnum.S, "A good encourager",
    DiscEnum.I, DiscEnum.I, "A good listener",
    DiscEnum.Star, DiscEnum.D, "A good analyzer",
    DiscEnum.C, DiscEnum.D, "A good delegator"),
    new MostLeastQuestionsModel(23,
    DiscEnum.S, DiscEnum.S, "Rules need to be challenged",
    DiscEnum.I, DiscEnum.I, "Rules make it fair",
    DiscEnum.Star, DiscEnum.D, "Rules make it boring",
    DiscEnum.C, DiscEnum.D, "Rules make it safe"),
    new MostLeastQuestionsModel(24,
    DiscEnum.S, DiscEnum.S, "Reliable, Dependable",
    DiscEnum.I, DiscEnum.I, "Creative, Unique",
    DiscEnum.Star, DiscEnum.D, "Bottom line, Results oriented",
    DiscEnum.C, DiscEnum.D, "Hold high standards, Accurate")
];