import { DiscEnum } from '../../models/discEnum';
import MostLeastQuestionsModel from '../../models/mostLeastQuestionsModel'

export const QuestionsList = [
    new MostLeastQuestionsModel(1,
    DiscEnum.S, DiscEnum.S, "Easy-going, Agreeable",
    DiscEnum.I, DiscEnum.I, "Trusting, Believing in others",
    DiscEnum.Star, DiscEnum.D, "Adventurous, Risk taker",
    DiscEnum.C, DiscEnum.D, "Tolerant, Respectful"),
    new MostLeastQuestionsModel(2,
    DiscEnum.D, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.C, "",
    DiscEnum.Star, DiscEnum.I, "",
    DiscEnum.Star2, DiscEnum.S, ""),
    new MostLeastQuestionsModel(3,
    DiscEnum.Star, DiscEnum.C, "",
    DiscEnum.D, DiscEnum.D, "",
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.Star, ""),

    new MostLeastQuestionsModel(4,
    DiscEnum.C, DiscEnum.Star, "",
    DiscEnum.D, DiscEnum.D, "",
    DiscEnum.Star, DiscEnum.I, "",
    DiscEnum.S, DiscEnum.S, ""),
    new MostLeastQuestionsModel(5,
    DiscEnum.Star, DiscEnum.C, "",
    DiscEnum.D, DiscEnum.D, "",
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.Star, ""),
    new MostLeastQuestionsModel(6,
    DiscEnum.D, DiscEnum.D, "",
    DiscEnum.Star, DiscEnum.I, "",
    DiscEnum.Star2, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.Star, ""),

    new MostLeastQuestionsModel(7,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(8,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(9,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(10,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(11,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(12,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(13,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(14,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(15,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(16,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(17,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(18,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(19,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(20,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(21,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(22,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(23,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, ""),
    new MostLeastQuestionsModel(24,
    DiscEnum.S, DiscEnum.S, "",
    DiscEnum.I, DiscEnum.I, "",
    DiscEnum.Star, DiscEnum.D, "",
    DiscEnum.C, DiscEnum.D, "")
];